name       : ldc
version    : 1.16.0
release    : 16
source     :
    - git|https://github.com/ldc-developers/ldc.git : v1.16.0
    - https://github.com/ldc-developers/ldc/releases/download/v1.16.0/ldc2-1.16.0-linux-x86_64.tar.xz : fbd31d36dd679359f41e28abc58dd6817770c7c80ee5f427f97b5d1d1b1f4ae3
license    :
    - BSD-3-Clause
    - BSL-1.0
    - GPL-2.0
component  : programming
summary    : The LLVM-based D Compiler
description: |
    The LDC project provides a portable D programming language compiler with modern optimization and code generation capabilities. The compiler uses the official DMD frontend to support the latest version of D2, and relies on the LLVM Core libraries for code generation.
clang      : yes
libsplit   : no
patterns   :
    - /usr/include/*
    - /usr/lib64/*
builddeps  :
    - ldc
    - binutils-gold
setup      : |
    %patch -p1 < $pkgfiles/dont-force-gold.patch

    mkdir ldc-host
    tar xvf $sources/ldc2-1.16.0-linux-x86_64.tar.xz -C $workdir/ldc-host --strip-components=1

    export LDFLAGS="$LDFLAGS -fuse-ld=ld"

    mkdir bootstrap && pushd bootstrap
    cmake -G Ninja .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DD_COMPILER=$workdir/ldc-host/bin/ldmd2 \
        -DBUILD_SHARED_LIBS=OFF \
        -DLDC_WITH_LLD=OFF \
        -DCMAKE_INSTALL_PREFIX=$workdir/ldc-bootstrap \
    ..
    ninja install %JOBS%
    popd
build      : |
    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DLIB_SUFFIX=64 \
        -DBUILD_SHARED_LIBS=ON \
        -DINCLUDE_INSTALL_DIR=/usr/include/dlang/ldc \
        -DLDC_WITH_LLD=OFF \
        -DD_COMPILER=$workdir/ldc-bootstrap/bin/ldmd2
    %ninja_build
install    : |
    %ninja_install
check      : |
    #pushd solusBuildDir
    #ninja all-test-runners
    #ctest --output-on-failure -R "ldc2-unittest"
