name       : ldc
version    : 1.9.0
release    : 3
source     :
    - git|https://github.com/ldc-developers/ldc.git : v1.9.0
license    :
    - BSD-3-Clause
    - BSL-1.0
    - GPL-2.0
component  : programming
summary    : The LLVM-based D Compiler
description: |
    The LDC project provides a portable D programming language compiler with modern optimization and code generation capabilities. The compiler uses the official DMD frontend to support the latest version of D2, and relies on the LLVM Core libraries for code generation.
clang      : yes
libsplit   : no
patterns   :
    - /usr/include/*
    - /usr/lib64/*
builddeps  :
    - dmd
setup      : |
    %cmake_ninja \
        -DLIB_SUFFIX=64 \
        -DBUILD_SHARED_LIBS=ON \
        -DINCLUDE_INSTALL_DIR=/usr/include/dlang/ldc
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    # We seem to have missing symbols very similar
    # to this bug: https://github.com/NixOS/nixpkgs/issues/28896
    #%ninja_check || :
