name       : ldc
version    : 1.18.0
release    : 20
source     :
    - git|https://github.com/ldc-developers/ldc.git : v1.18.0
    - https://github.com/ldc-developers/ldc/releases/download/v1.18.0/ldc2-1.18.0-linux-x86_64.tar.xz : 04ba1573fb9c728d555340249b8d54cf7d34d249ea185a240be7ab341c764cf5
license    :
    - BSD-3-Clause
    - BSL-1.0
    - GPL-2.0
component  : programming
summary    : The LLVM-based D Compiler
description: |
    The LDC project provides a portable D programming language compiler with modern optimization and code generation capabilities. The compiler uses the official DMD frontend to support the latest version of D2, and relies on the LLVM Core libraries for code generation.
clang      : yes
libsplit   : no
patterns   :
    - /usr/include/*
    - /usr/lib64/*
builddeps  :
    - ldc
    - binutils-gold
setup      : |
    %patch -p1 < $pkgfiles/stateless.patch
    %patch -p1 < $pkgfiles/dont-force-gold.patch

    mkdir ldc-host
    tar xvf $sources/ldc2-1.18.0-linux-x86_64.tar.xz -C $workdir/ldc-host --strip-components=1

    export LDFLAGS="$LDFLAGS -fuse-ld=ld"

    # github.com/ldc-developers/ldc/issues/3079
    sed -i '/FileCheck/,$d' utils/CMakeLists.txt

    mkdir bootstrap && pushd bootstrap
    cmake -G Ninja .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_SHARED_LIBS=OFF \
        -DLDC_WITH_LLD=OFF \
        -DCMAKE_INSTALL_PREFIX=$workdir/ldc-bootstrap \
        -DD_COMPILER=$workdir/ldc-host/bin/ldmd2

    ninja install %JOBS%
    popd
build      : |
    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DLIB_SUFFIX=64 \
        -DBUILD_SHARED_LIBS=ON \
        -DINCLUDE_INSTALL_DIR=/usr/include/dlang/ldc \
        -DSYSCONF_INSTALL_DIR=/usr/share/defaults/etc \
        -DLDC_WITH_LLD=OFF \
        -DD_COMPILER=$workdir/ldc-bootstrap/bin/ldmd2
    %ninja_build
install    : |
    %ninja_install
check      : |
    #pushd solusBuildDir
    #ninja all-test-runners
    #ctest --output-on-failure -R "ldc2-unittest"
