name       : ldc
version    : 1.26.0
release    : 36
source     :
    - git|https://github.com/ldc-developers/ldc.git : v1.26.0
license    :
    - Apache-2.0
    - BSD-3-Clause
    - BSL-1.0
component  : programming
summary    : The LLVM-based D Compiler
description: |
    The LDC project provides a portable D programming language compiler with modern optimization and code generation capabilities. The compiler uses the official DMD frontend to support the latest version of D2, and relies on the LLVM Core libraries for code generation.
clang      : yes
libsplit   : no
patterns   :
    - /usr/include/*
    - /usr/lib64/*
builddeps  :
    - ldc
setup      : |
    %patch -p1 < $pkgfiles/stateless.patch
    #patch -p1 < $pkgfiles/0001-dont-use-lto-and-or-pgo.patch
    %patch -p1 < $pkgfiles/0001-use-bfd-instead-of-gold.patch

    mkdir bootstrap && pushd bootstrap
    cmake -G Ninja .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_SHARED_LIBS=OFF \
        -DLDC_WITH_LLD=OFF \
        -DCMAKE_INSTALL_PREFIX=$workdir/ldc-bootstrap \
    ..
    ninja install %JOBS%
    popd
build      : |
    %cmake_ninja \
        -DLIB_SUFFIX=64 \
        -DBUILD_SHARED_LIBS=BOTH \
        -DBUILD_LTO_LIBS=ON \
        -DINCLUDE_INSTALL_DIR=/usr/include/dlang/ldc \
        -DSYSCONF_INSTALL_DIR=/usr/share/defaults/etc \
        -DLDC_WITH_LLD=OFF \
        -DD_COMPILER=$workdir/ldc-bootstrap/bin/ldmd2 \
        -DADDITIONAL_DEFAULT_LDC_SWITCHES="\"-link-defaultlib-shared\""
    %ninja_build
install    : |
    %ninja_install
# Takes an age
#check      : |
#    %ninja_check
